// <auto-generated />
using System;
using EntityFrameworkCore.Jet.Metadata;
using Netade.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Netade.Persistence.Migrations
{
    [DbContext(typeof(NetadeDbContext))]
    [Migration("20240326135520_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Netade.Domain.Database", b =>
                {
                    b.Property<int>("DatabaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("counter")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("DatabaseId");

                    b.ToTable("Databases");
                });

            modelBuilder.Entity("Netade.Domain.DatabaseLogin", b =>
                {
                    b.Property<int>("DatabaseLoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("counter")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DatabaseId")
                        .HasColumnType("integer");

                    b.Property<int>("LoginId")
                        .HasColumnType("integer");

                    b.HasKey("DatabaseLoginId")
                        .HasName("PrimaryKey");

                    b.HasIndex("LoginId");

                    b.HasIndex(new[] { "DatabaseId", "LoginId" }, "DatabaseLogin")
                        .IsUnique();

                    b.ToTable("DatabaseLogins");
                });

            modelBuilder.Entity("Netade.Domain.Login", b =>
                {
                    b.Property<int>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("counter")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("No");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginId")
                        .HasName("PrimaryKey");

                    b.HasIndex(new[] { "LoginName" }, "uniqlogin")
                        .IsUnique();

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("Netade.Domain.DatabaseLogin", b =>
                {
                    b.HasOne("Netade.Domain.Database", "Database")
                        .WithMany("DatabaseLogins")
                        .HasForeignKey("DatabaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("DatabasesDatabaseLogins");

                    b.HasOne("Netade.Domain.Login", "Login")
                        .WithMany("DatabaseLogins")
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("LoginsDatabaseLogins");

                    b.Navigation("Database");

                    b.Navigation("Login");
                });

            modelBuilder.Entity("Netade.Domain.Database", b =>
                {
                    b.Navigation("DatabaseLogins");
                });

            modelBuilder.Entity("Netade.Domain.Login", b =>
                {
                    b.Navigation("DatabaseLogins");
                });
#pragma warning restore 612, 618
        }
    }
}
